pub mod error;
pub mod value;
pub mod tensor;
pub mod env;
pub mod pattern;
pub mod agent_client;
pub mod ir;
pub mod ast_to_ir;
pub mod bytecode;
pub mod bytecode_compiler;
pub mod bytecode_vm;
pub mod bytecode_marshal;
pub mod contract_signal;
#[cfg(feature = "aot")]
pub mod bytecode_aot;

// Convenience re-exports
pub use error::RuntimeError;
pub use value::Value;
pub use env::Env;
pub use pattern::try_match;
