#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AIRL_DIR="${AIRL_DIR:-$HOME/repos/AIRL}"
G3="${G3:-$AIRL_DIR/g3}"
AT_ROOT="${AT_ROOT:-$HOME/repos/AirTraffic}"
export AIRL_STDLIB="${AIRL_STDLIB:-$AIRL_DIR/stdlib}"

if [[ ! -x "$G3" ]]; then
    echo "Error: g3 compiler not found at $G3"
    echo "Build it: cd ~/repos/AIRL && bash scripts/build-g3.sh"
    exit 1
fi

# ─── Generate _generated.airl with embedded guide + version ──────────
GUIDE_FILE="$AIRL_DIR/AIRL-LLM-Guide.md"
if [[ ! -f "$GUIDE_FILE" ]]; then
    echo "Error: AIRL-LLM-Guide.md not found at $GUIDE_FILE"
    exit 1
fi

# Extract version from Cargo.toml
VERSION=$(grep '^version' "$AIRL_DIR/Cargo.toml" | head -1 | sed 's/.*"\(.*\)".*/\1/')

# Escape guide content for AIRL string literal: \ → \\, " → \", newlines → \n
ESCAPED_GUIDE=$(awk '{
    gsub(/\\/, "\\\\")
    gsub(/"/, "\\\"")
    if (NR > 1) printf "\\n"
    printf "%s", $0
}' "$GUIDE_FILE")

# g3 segfaults on string literals >~45K chars, so split into chunks.
# Use 25K char chunks for safety margin.
CHUNK_SIZE=25000
TOTAL_LEN=${#ESCAPED_GUIDE}
NUM_CHUNKS=$(( (TOTAL_LEN + CHUNK_SIZE - 1) / CHUNK_SIZE ))

{
    echo ";; _generated.airl — auto-generated by build.sh (do not edit)"
    echo ""

    for ((i=0; i<NUM_CHUNKS; i++)); do
        OFFSET=$((i * CHUNK_SIZE))
        CHUNK="${ESCAPED_GUIDE:$OFFSET:$CHUNK_SIZE}"
        echo "(defn mni-guide-chunk-$i"
        echo "  :sig [-> String]"
        echo "  :body \"${CHUNK}\")"
        echo ""
    done

    # Concatenate all chunks — str is binary, so nest: (str (str a b) c)
    printf "(defn mni-embedded-guide\n  :sig [-> String]\n  :body "
    if [[ $NUM_CHUNKS -eq 1 ]]; then
        printf "(mni-guide-chunk-0)"
    else
        # Build nested (str (str (str a b) c) d) left-to-right
        EXPR="(mni-guide-chunk-0)"
        for ((i=1; i<NUM_CHUNKS; i++)); do
            EXPR="(str ${EXPR} (mni-guide-chunk-${i}))"
        done
        printf "%s" "$EXPR"
    fi
    echo ")"
    echo ""

    echo "(defn mni-version"
    echo "  :sig [-> String]"
    echo "  :body \"${VERSION}\")"
} > "$SCRIPT_DIR/_generated.airl"

echo "Generated _generated.airl (version ${VERSION}, guide $(wc -l < "$GUIDE_FILE") lines, ${NUM_CHUNKS} chunks)"

# json.airl provides json-parse/json-stringify (needed by jsonrpc.airl).
# patch-prompts-list.airl is listed BEFORE airtraffic.airl so the local
# airtraffic-handle-prompts-list fix (first-def-wins) takes effect.
# _generated.airl must come BEFORE mynameisairl.airl (which calls its functions).
# mynameisairl.airl must be LAST since its top-level code is the entry point.
"$G3" -- \
    "$AIRL_DIR/stdlib/json.airl" \
    "$AT_ROOT/src/transport.airl" \
    "$AT_ROOT/src/jsonrpc.airl" \
    "$AT_ROOT/src/schema.airl" \
    "$SCRIPT_DIR/patch-prompts-list.airl" \
    "$SCRIPT_DIR/_generated.airl" \
    "$AT_ROOT/src/airtraffic.airl" \
    "$SCRIPT_DIR/mynameisairl.airl" \
    -o "${1:-$SCRIPT_DIR/mynameisairl}"
