#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AIRL_DIR="${AIRL_DIR:-$HOME/repos/AIRL}"
G3="${G3:-$AIRL_DIR/g3}"
AT_ROOT="${AT_ROOT:-$HOME/repos/AirTraffic}"
export AIRL_STDLIB="${AIRL_STDLIB:-$AIRL_DIR/stdlib}"

if [[ ! -x "$G3" ]]; then
    echo "Error: g3 compiler not found at $G3"
    echo "Build it: cd ~/repos/AIRL && bash scripts/build-g3.sh"
    exit 1
fi

OUTPUT="${1:-$SCRIPT_DIR/mynameisairl}"
OUTPUT_DIR="$(dirname "$OUTPUT")"

# ─── Copy guide next to binary ──────────────────────────────────────
GUIDE_FILE="$AIRL_DIR/AIRL-LLM-Guide.md"
if [[ ! -f "$GUIDE_FILE" ]]; then
    echo "Error: AIRL-LLM-Guide.md not found at $GUIDE_FILE"
    exit 1
fi
cp "$GUIDE_FILE" "$OUTPUT_DIR/AIRL-LLM-Guide.md"

# ─── Generate _generated.airl with version only ─────────────────────
VERSION=$(grep '^version' "$AIRL_DIR/Cargo.toml" | head -1 | sed 's/.*"\(.*\)".*/\1/')

cat > "$SCRIPT_DIR/_generated.airl" << EOF
;; _generated.airl — auto-generated by build.sh (do not edit)

(defn mni-version
  :sig [-> String]
  :body "${VERSION}")
EOF

echo "Generated _generated.airl (version ${VERSION}), copied guide ($(wc -l < "$GUIDE_FILE") lines)"

# json.airl provides json-parse/json-stringify (needed by jsonrpc.airl).
# patch files are listed BEFORE airtraffic.airl so first-def-wins applies.
# AirMunch source files must come after airtraffic (they use its functions)
# but before mynameisairl.airl (the entry point, which must be LAST).
"$G3" -- \
    "$AIRL_DIR/stdlib/json.airl" \
    "$AIRL_DIR/stdlib/sha256.airl" \
    "$AIRL_DIR/stdlib/path.airl" \
    "$AT_ROOT/src/transport.airl" \
    "$AT_ROOT/src/jsonrpc.airl" \
    "$AT_ROOT/src/schema.airl" \
    "$SCRIPT_DIR/patch-prompts-list.airl" \
    "$SCRIPT_DIR/patch-json-result.airl" \
    "$SCRIPT_DIR/patch-tool-allowed.airl" \
    "$SCRIPT_DIR/_generated.airl" \
    "$AT_ROOT/src/airtraffic.airl" \
    "$SCRIPT_DIR/src/sexpr-reader.airl" \
    "$SCRIPT_DIR/src/symbol-extract.airl" \
    "$SCRIPT_DIR/src/index-store.airl" \
    "$SCRIPT_DIR/src/search.airl" \
    "$SCRIPT_DIR/src/xref.airl" \
    "$SCRIPT_DIR/src/tools.airl" \
    "$SCRIPT_DIR/mynameisairl.airl" \
    -o "$OUTPUT"
